### ISSUE TITLE
Training get IoU=0.0 after 60 epochs.

### ISSUE THREAD

**Issue by synsin0** [wzzheng/OccWorld#4]
I clone the repo and execute the command: python train.py --py-config config/occworld.py --work-dir out/occworld on 4 GPUs. I guess I omit the command: 'a VQVAE should be trained using similar command before training' and gets almost no accuracy. May you explain more in detail how to train VQVAE first and train OccWorld next?

**Comment by chen-wl20** [comment]
Thank you for your interest!
The network structure for VQVAE can be found in the 'occworld.py' file. Since no specific techniques were employed during the training of VQVAE, I haven't included a dedicated config file for it. You can attempt to train VQVAE initially and then integrate it into the occworld. I may organize this section of the file at a later time when I have the opportunity. Feel free to stay tuned for updates
